### ISSUE TITLE
lfdl-landscape npm run build error!

### ISSUE THREAD

**Issue by dongjiang1989** [cncf/landscapeapp#207]
### This is the upstream landscapeapp

  console.info specs/main.spec.js:26
    retrying... { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577
        at onTimeout (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/puppeteer/lib/Launcher.js:353:14)
        at Timeout.callback (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }

If you want to modify the content in the CNCF or LFDL landscapes, please make changes to those downstream repos:
* https://github.com/cncf/landscape
* https://github.com/LFDLFoundation/lfdl-landscape

**Comment by dankohn** [comment]
Closing as I can't replicate. Please feel free to reopen with more details.
