### ISSUE TITLE
`LEVEL=complete npm run fetch` throws error

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#309]
Getting error:

```js
{ Error: ENOENT: no such file or directory, open '/Users/jordi/workspace/omp-landscape/processed_landscape.yml'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at readFileSync (/Users/jordi/workspace/landscapeapp/tools/addExternalInfo.js:266:73)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/Users/jordi/workspace/omp-landscape/processed_landscape.yml' }
```

**Comment by dankohn** [comment]
That's because we haven't used that feature in more than a year, so it rusted. We can either fix or remove. You get the same effect by deleting `processed_landscape` and running `yf`.
