### ISSUE TITLE
Error: spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#375]
I can no longer run `y build`:

```
visiting http://localhost:4000/landscape?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/serverless?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/members?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/members?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/serverless?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/landscape?preview&version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/landscape?version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/serverless?version=2019-09-30T17:56:28Z c0e5b1f
visiting http://localhost:4000/members?version=2019-09-30T17:56:28Z c0e5b1f

> interactive-landscape@1.0.269 stop-ci /Users/dan/Dropbox/Documents/dev/landscape/node_modules/interactive-landscape
> kill -9 `cat /tmp/ci.pid` && rm /tmp/ci.pid

From https://github.com/cncf/landscape
 * [new branch]      master                  -> github/master
 * [new branch]      taylorwaggoner-chinaunicom -> github/taylorwaggoner-chinaunicom
 * [new branch]      taylorwaggoner-new-members-1 -> github/taylorwaggoner-new-members-1
 * [new branch]      taylorwaggoner-redhat-1 -> github/taylorwaggoner-redhat-1

child_process.js:660
    throw err;
    ^

Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execSync (child_process.js:652:15)
    at execSync (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/interactive-landscape/tools/fundingHistoryData.js:14:44)
    at getFileFromHistory (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/interactive-landscape/tools/fundingHistoryData.js:72:25)
    at Array.forEach (<anonymous>)
    at Object.forEach (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/interactive-landscape/tools/fundingHistoryData.js:68:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._compile (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/interactive-landscape/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10) {
  errno: 'ENOBUFS',
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    "cd '/Users/dan/Dropbox/Documents/dev/landscape'; git show f7b7217629911d5f691b921ea1998ba1b694d495:processed_landscape.yml"
  ],
  error: [Circular],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 23 20 54 48 49 53 20 46 49 4c 45 20 49 53 20 47 45 4e 45 52 41 54 45 44 20 41 55 54 4f 4d 41 54 49 43 41 4c 4c 59 21 0a 6c 61 6e 64 73 63 61 70 65 3a ... 1056718 more bytes>,
    <Buffer >
  ],
  pid: 19016,
  stdout: <Buffer 23 20 54 48 49 53 20 46 49 4c 45 20 49 53 20 47 45 4e 45 52 41 54 45 44 20 41 55 54 4f 4d 41 54 49 43 41 4c 4c 59 21 0a 6c 61 6e 64 73 63 61 70 65 3a ... 1056718 more bytes>,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interactive-landscape@1.0.269 build: `((babel-node tools/build.js && npm run copy-dist && npm run setup-robots && npm run stop-old-ci && npm run start-ci && npm run integration-test && npm run check-landscape && npm run render-landscape) || (npm run stop-old-ci && false)) && npm run stop-ci && babel-node tools/fundingForMasterBranch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-landscape@1.0.269 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dan/.npm/_logs/2019-09-30T17_58_13_778Z-debug.log
```

**Comment by jordinl83** [comment]
@dankohn it worked for me. Do you have local changes?

**Comment by dankohn** [comment]
No, I've stashed local changes. This is the problem on HEAD. Could you please try to implement this flag?

https://github.com/lerna/lerna/issues/479
https://github.com/lerna/lerna/pull/782

**Comment by AndreyKozlov1984** [comment]
I was not able to reproduce. Is this fixed already?

**Comment by AndreyKozlov1984** [comment]
`maxBuffer` equal to 100 * 1000 * 1000 is an options which I'm about to add to spawnSync

**Comment by dankohn** [comment]
Once I checkout this branch, how do I execute if landscapeapp and landscape are sibling directories?

**Comment by AndreyKozlov1984** [comment]
I think you can run with a `PROJECT_PATH=../landscape npm run build` from a landscapeapp
