### ISSUE TITLE
Funding bug in LFAI

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#388]
https://app.netlify.com/sites/lfailandscape/deploys/5d9e642c1e376e000c61ceb6
https://github.com/lfai/lfai-landscape/compare/ihaddad-newprojs
```
6:57:32 PM: /opt/build/repo/node_modules/interactive-landscape/tools/fundingHistoryPage.js:46
6:57:32 PM:                  <td>${_settings.settings.membership[item.membership].funding}</td>
6:57:32 PM:                                                                       ^
6:57:32 PM: TypeError: Cannot read property 'funding' of undefined
6:57:32 PM:     at funding (/opt/build/repo/node_modules/interactive-landscape/tools/fundingHistoryPage.js:38:61)
6:57:32 PM:     at Array.map (<anonymous>)
6:57:32 PM:     at Object.map (/opt/build/repo/node_modules/interactive-landscape/tools/fundingHistoryPage.js:31:19)
6:57:32 PM:     at Module._compile (internal/modules/cjs/loader.js:734:30)
6:57:32 PM:     at Module._compile (/opt/build/repo/node_modules/interactive-landscape/node_modules/pirates/lib/index.js:99:24)
6:57:32 PM:     at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
6:57:32 PM:     at Object.newLoader [as .js] (/opt/build/repo/node_modules/interactive-landscape/node_modules/pirates/lib/index.js:104:7)
6:57:32 PM:     at Module.load (internal/modules/cjs/loader.js:626:32)
6:57:32 PM:     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
6:57:32 PM:     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```
Could you please try to see the cause of this bug. I can replicate locally.

**Comment by dankohn** [comment]
Fixed with https://github.com/lfai/lfai-landscape/commit/b6b7392140cba6bd3869e801eac12401eaf103ec#diff-98126fffe52a5bcbb73fa2926d7732dd
