### ISSUE TITLE
yo doesn't work

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#614]
I blew away `landscapeapp/node_modules` and reinstalled but the same error recurred:

```
$ yo

> interactive-landscape@1.0.432 open:src /Users/dan/Dropbox/Documents/dev/landscapeapp
> npm run yaml2json && babel-node tools/srcServer.js


> interactive-landscape@1.0.432 yaml2json /Users/dan/Dropbox/Documents/dev/landscapeapp
> babel-node tools/generateJson.js

processed /Users/dan/Dropbox/Documents/dev/lfph-landscape
Fetching members from LFPH Member category
Processing the tree
Server is running on http://localhost:3000
ℹ ｢wdm｣: wait until bundle finished: /
webpack built 26218acdf51f29dd3f9e in 9734ms
✖ ｢wdm｣: Built at: 06/13/2020 1:01:13 AM
Entrypoint main = bundle.js
[0] multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js 64 bytes {main} [built]
[../lfph-landscape/images/favicon.png] 55 bytes {main} [built]
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {main} [built]
[./node_modules/current-device/es/index.js] 8.21 KiB {main} [built]
[./node_modules/iframe-resizer/js/iframeResizer.contentWindow.js] 33.6 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-ga/dist/esm/index.js] 2.09 KiB {main} [built]
[./node_modules/react-hot-loader/dist/react-hot-loader.development.js] 97.1 KiB {main} [built]
[./node_modules/react-hot-loader/index.js] 1.55 KiB {main} [built]
[./node_modules/react-hot-loader/patch.js] 229 bytes {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.68 KiB {main} [built]
[./src/index.js] 5.49 KiB {main} [built]
[./src/webpack-public-path.js] 124 bytes {main} [built]
    + 1352 hidden modules

ERROR in ./src/styles/theme.scss (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??ref--12-2!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./src/styles/theme.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:974:3)
    at Object.getInstalledBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.newLoader [as .js] (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getDefaultSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/styles/theme.scss 2:26-216 43:4-64:5 46:18-208
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

ERROR in ./src/styles/roboto.css (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??ref--12-2!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./src/styles/roboto.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:974:3)
    at Object.getInstalledBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.newLoader [as .js] (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getDefaultSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/styles/roboto.css 2:26-216 43:4-64:5 46:18-208
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

ERROR in ./src/styles/itemModal.scss (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??ref--12-2!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./src/styles/itemModal.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:974:3)
    at Object.getInstalledBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.newLoader [as .js] (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getDefaultSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/styles/itemModal.scss 2:26-220 43:4-64:5 46:18-212
 @ ./src/components/ItemDialog.js
 @ ./src/components/ItemDialogContainer.js
 @ ./src/components/HomePage.js
 @ ./src/components/HomePageContainer.js
 @ ./src/components/App.js
 @ ./src/components/Root.js
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js
Child HtmlWebpackCompiler:
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 531 bytes {HtmlWebpackPlugin_0} [built] [failed] [1 error]
    
    ERROR in ./src/index.ejs (./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs)
    Module build failed (from ./node_modules/ejs-loader/index.js):
    Error: 
          To support the 'esModule' option, the 'variable' option must be passed to avoid 'with' statements
          in the compiled template to be strict mode compatible. Please see https://github.com/lodash/lodash/issues/3709#issuecomment-375898111.
          To enable CommonJS, please set the 'esModule' option to false.
        
        at Object.module.exports (/Users/dan/Dropbox/Documents/dev/landscapeapp/node_modules/ejs-loader/index.js:12:11)
ℹ ｢wdm｣: Failed to compile.
```

**Comment by AndreyKozlov1984** [comment]
Fixed the `esModule` error in a master branch, regarding the sass, beside the obvious idea to get rid of it, we have an `npm cache clean`. Another thing which may help is `npm rebuild node-sass`

**Comment by AndreyKozlov1984** [comment]
This is also a way to get rid of previous node-sass - `rm -rf node_modules/ ~/.npm/*`

**Comment by AndreyKozlov1984** [comment]
Everything has been fixed.
