### ISSUE TITLE
Netlify reports error in `landscape.js`

### ISSUE THREAD

**Issue by seabass-labrax** [cncf/landscapeapp#782]
Greetings! I've been working with @kestewart to create a landscape page for the tooling ecosystem around [SPDX](https://spdx.dev). Yesterday, though, the Netlify build failed. It appears to be something to do with a failing SSH connection to svg.cncf.io:

```
1:00:29 AM:       mkdir -p distRemote
1:00:29 AM:       rsync -az --chmod=a+r -p -e "ssh -i /tmp/buildbot  -o StrictHostKeyChecking=no " root@147.75.76.177:/root/builds/landscape16349471785060.5736426528265279/dist/* distRemote    , exit code: 23    at runLocalWithoutErrors (/opt/build/repo/netlify/landscape.js:90:11)    at async makeRemoteBuildWithCache (/opt/build/repo/netlify/landscape.js:343:16)    at async Promise.all (index 0)    at async main (/opt/build/repo/netlify/landscape.js:402:3)​
1:00:29 AM: ────────────────────────────────────────────────────────────────
1:00:29 AM:   "build.command" failed
```
The full log is attached here: [netlify-log.txt](https://github.com/cncf/landscapeapp/files/7403091/netlify-log.txt)

Any pointers here would be very much appreciated. Thanks!

**Comment by seabass-labrax** [comment]
Since filing this issue, some release builds on the SBOM Landscape page have succeeded but all the pull request preview builds have failed.
